### ISSUE TITLE
Client side validation of Signup and logIn

### ISSUE THREAD

**Issue by Usman-Alii** [bilalshahzad139/EADProject#25] opened 2020-05-07 17:44 UTC
Input Validation

**Comment by abdurrahman-asad** [comment] 2020-05-07 17:52
This issue is already created. Please refer to #9 .
Please talk to them to include you as an assignee if you want to work on this.
@bilalshahzad139

**Comment by MughalUsama** [comment] 2020-05-07 17:54
@Usman-Alii  validation or testing?
Validation is done in #9 and testing in #11

**Comment by abdurrahman-asad** [comment] 2020-05-07 17:57
I've closed this issue as its duplicate of #9

**Closed as completed** 2020-05-07 17:57 UTC
Labels: duplicate, enhancement

**Comment by Ali-Bhatti** [comment] 2020-05-07 18:30
Mark it as duplicate
